version: '3.9'

services:
  web:
    build:
      context: .
    command: gunicorn Gabrielle_Kourdadze.wsgi:application --bind 0.0.0.0:8000 --workers 3
    volumes:
      - .:/app
    expose:
      - "8000"  # Expose port to internal network for nginx
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DEBUG=${DEBUG}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"  # Map host's port 80 to nginx
    depends_on:
      - web  # nginx depends on the web service to be up
