version: "3.9"

services:
  web:
    container_name: web-landing
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/local
    entrypoint: ""
    command: bash -c "python manage.py makemigrations &&
                      python manage.py migrate --noinput &&
                      python manage.py runserver 0.0.0.0:8000"
