version: "3.9"

services:
  web:
    build: .
    command: gunicorn Gabrielle_Kourdadze.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
      - ./db.sqlite3:/app/db.sqlite3
