# Generated by Django 3.2.12 on 2024-11-28 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exhibition',
            name='date',
        ),
        migrations.RemoveField(
            model_name='exhibition',
            name='description',
        ),
    ]
