# Generated by Django 3.2.12 on 2024-12-01 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20241128_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
