# Generated by Django 3.2.12 on 2024-12-01 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_painting_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workonpaper',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
