# Generated by Django 3.2.12 on 2024-12-02 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_alter_workonpaper_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='textspublications',
            old_name='full_text',
            new_name='publication',
        ),
        migrations.RenameField(
            model_name='textspublications',
            old_name='mini_description',
            new_name='subtitle',
        ),
        migrations.AlterField(
            model_name='textspublications',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
