# Generated by Django 3.2.12 on 2024-12-02 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_auto_20241202_1353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='textspublications',
            old_name='publication',
            new_name='publication_en',
        ),
        migrations.RenameField(
            model_name='textspublications',
            old_name='subtitle',
            new_name='subtitle_en',
        ),
        migrations.RenameField(
            model_name='textspublications',
            old_name='title',
            new_name='title_en',
        ),
        migrations.AddField(
            model_name='textspublications',
            name='publication_fr',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='textspublications',
            name='subtitle_fr',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='textspublications',
            name='title_fr',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
