# Generated by Django 3.2.12 on 2024-12-02 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_auto_20241202_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='education',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='fair',
            name='date',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='fair',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='groupexhibition',
            name='date',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='groupexhibition',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='personalexhibition',
            name='date',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='personalexhibition',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='residency',
            name='location',
            field=models.CharField(max_length=500),
        ),
    ]
