# Generated by Django 3.2.12 on 2024-12-05 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_auto_20241202_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibitionimage',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='exhibitions/thumbnails/'),
        ),
        migrations.AddField(
            model_name='painting',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='paintings/thumbnails/'),
        ),
        migrations.AddField(
            model_name='workonpaper',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='works-on-paper/thumbnails/'),
        ),
    ]
